### PR TITLE
#27 Update to version [5][5] of LVB API

### PR DESCRIPTION
**Pull request by joergreichert**

### CODE REVIEW

**Comment by hashworks** [comment]
A test failes for me:
```
# lvb.journeys
not ok 6 TypeError: Cannot read property '1t0' of undefined
  ---
    operator: error
    at: bound (node_modules/onetime/index.js:30:12)
    stack: |-
      TypeError: Cannot read property '1t0' of undefined
          at transformTariffs (lib/journeys.js:73:18)
          at transformJourney (lib/journeys.js:89:9)
          at Array.map (<anonymous>)
          at lib/journeys.js:144:22
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
          at async test.js:52:19
  ...
```

**Comment by joergreichert** [comment]
Seems to be an issue with the new API version, it only returns

```
"tariffs": {
                "zones": "",
                "zone_start": "",
                "zone_end": ""
            }
```


this is the complete response (I've used lvb.de and it also doesn't show any tariff information anymore).  

```
{
    "is_extended": {
        "is_extended": "",
        "from_opt": "3",
        "from": "Leipzig, Deutsche Nationalbibliothek",
        "from_lat": "",
        "from_lng": "",
        "to_opt": "3",
        "to": "Leipzig, Messegel\u00e4nde",
        "to_lat": "",
        "to_lng": "",
        "via": "",
        "via_lat": "",
        "via_lng": "",
        "time_mode": "departure",
        "time": "08:31",
        "date": "11.10.2020",
        "mode": "connection"
    },
    "context": "dq.03044661.1602397977#1",
    "connections": {
        "C1-0": {
            "duration": "00:34",
            "transfers": 0,
            "date": "11.10.2020",
            "departure": {
                "datetime": "20201011081400",
                "station": "Leipzig, Deutsche Nationalbibliothek",
                "shifting": 1,
                "hasPrognosis": {
                    "date": "2020-10-11 08:15:00.000000",
                    "timezone_type": 3,
                    "timezone": "Europe\/Berlin"
                }
            },
            "arrival": {
                "datetime": "20201011084800",
                "station": "Leipzig, Messegel\u00e4nde"
            },
            "sections": [{
                    "from": {
                        "station": "Leipzig, Deutsche Nationalbibliothek",
                        "datetime": "20201011081400",
                        "delay": "1602396900",
                        "platform": "",
                        "shifting": 1,
                        "initialDepartureDelay": "00d08:15:00"
                    },
                    "to": {
                        "station": "Leipzig, Messegel\u00e4nde",
                        "datetime": "20201011084800",
                        "delay": "1602398940",
                        "platform": "",
                        "shifting": 1,
                        "arrivalDelay": {
                            "date": "2020-10-11 08:49:00.000000",
                            "timezone_type": 3,
                            "timezone": "Europe\/Berlin"
                        },
                        "arrivalTime": {
                            "date": "2020-10-11 08:48:00.000000",
                            "timezone_type": 3,
                            "timezone": "Europe\/Berlin"
                        }
                    },
                    "transport": "Str   16",
                    "line": "16",
                    "direction": "Messegel\u00e4nde",
                    "operator": "Leipziger Verkehrsbetriebe",
                    "type": "STN",
                    "duration": "00:34",
                    "delay": "00:34",
                    "length": 21,
                    "special": [],
                    "route": [{
                            "id": 11558,
                            "name": "Leipzig, Deutsche Nationalbibliothek",
                            "lat": 51.323561,
                            "lng": 12.395693,
                            "arr": "08:14",
                            "dep": "08:14",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 11557,
                            "name": "Leipzig, Johannisallee",
                            "lat": 51.3273,
                            "lng": 12.388789,
                            "arr": "08:15",
                            "dep": "08:15",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 10983,
                            "name": "Leipzig, Bayerischer Bahnhof (Tram\/Bus)",
                            "lat": 51.330509,
                            "lng": 12.380906,
                            "arr": "08:17",
                            "dep": "08:17",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 11584,
                            "name": "Leipzig, H\u00e4rtelstr.",
                            "lat": 51.332793,
                            "lng": 12.377544,
                            "arr": "08:19",
                            "dep": "08:19",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 13001,
                            "name": "Leipzig, Ro\u00dfplatz",
                            "lat": 51.336101,
                            "lng": 12.378587,
                            "arr": "08:20",
                            "dep": "08:20",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 13002,
                            "name": "Leipzig, Augustusplatz",
                            "lat": 51.338896,
                            "lng": 12.381994,
                            "arr": "08:22",
                            "dep": "08:22",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 13000,
                            "name": "Leipzig, Hauptbahnhof (Tram\/Bus)",
                            "lat": 51.343948,
                            "lng": 12.380331,
                            "arr": "08:25",
                            "dep": "08:30",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 11410,
                            "name": "Leipzig, Wilhelm-Liebknecht-Platz",
                            "lat": 51.349791,
                            "lng": 12.377589,
                            "arr": "08:32",
                            "dep": "08:32",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 12968,
                            "name": "Leipzig, Chausseehaus",
                            "lat": 51.356192,
                            "lng": 12.376996,
                            "arr": "08:34",
                            "dep": "08:34",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 12822,
                            "name": "Leipzig, Wilhelminenstr.",
                            "lat": 51.361486,
                            "lng": 12.381391,
                            "arr": "08:35",
                            "dep": "08:35",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 10980,
                            "name": "Leipzig, Eutritzscher Zentrum",
                            "lat": 51.36519,
                            "lng": 12.385185,
                            "arr": "08:36",
                            "dep": "08:36",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 12820,
                            "name": "Leipzig, Eutritzscher Markt",
                            "lat": 51.367698,
                            "lng": 12.38629,
                            "arr": "08:38",
                            "dep": "08:38",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 12821,
                            "name": "Leipzig, Mosenthinstr.",
                            "lat": 51.372597,
                            "lng": 12.385994,
                            "arr": "08:39",
                            "dep": "08:39",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 12818,
                            "name": "Leipzig, Delitzscher\/Essener Str.",
                            "lat": 51.376193,
                            "lng": 12.38549,
                            "arr": "08:40",
                            "dep": "08:40",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 12819,
                            "name": "Leipzig, Hornbach-Baumarkt",
                            "lat": 51.378988,
                            "lng": 12.384798,
                            "arr": "08:41",
                            "dep": "08:41",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 12816,
                            "name": "Leipzig, Klinikum St. Georg",
                            "lat": 51.384292,
                            "lng": 12.381194,
                            "arr": "08:42",
                            "dep": "08:42",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 12823,
                            "name": "Leipzig, Dachauer Str.",
                            "lat": 51.390099,
                            "lng": 12.377193,
                            "arr": "08:44",
                            "dep": "08:44",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 12824,
                            "name": "Leipzig, Wiederitzsch, Mitte",
                            "lat": 51.393398,
                            "lng": 12.375683,
                            "arr": "08:45",
                            "dep": "08:45",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 10823,
                            "name": "Leipzig, Georg-Herwegh-Str.",
                            "lat": 51.394881,
                            "lng": 12.383027,
                            "arr": "08:46",
                            "dep": "08:46",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 10824,
                            "name": "Leipzig, S-Bahnhof Messe (Tram\/Bus)",
                            "lat": 51.396041,
                            "lng": 12.388816,
                            "arr": "08:47",
                            "dep": "08:47",
                            "hasPrognosis": true,
                            "shifting": 1
                        }, {
                            "id": 10818,
                            "name": "Leipzig, Messegel\u00e4nde",
                            "lat": 51.396715,
                            "lng": 12.396574,
                            "arr": "08:48",
                            "dep": "",
                            "hasPrognosis": false,
                            "shifting": 0
                        }
                    ],
                    "color": "#017C46"
                }
            ],
            "types": {
                "stn": true
            },
            "tariffs": {
                "zones": "",
                "zone_start": "",
                "zone_end": ""
            }
        },
        "C1-1": {
            "duration": "00:34",
            "transfers": 0,
            "date": "11.10.2020",
            "departure": {
                "datetime": "20201011084400",
                "station": "Leipzig, Deutsche Nationalbibliothek",
                "shifting": 0,
                "hasPrognosis": {
                    "date": "2020-10-11 08:44:00.000000",
                    "timezone_type": 3,
                    "timezone": "Europe\/Berlin"
                }
            },
            "arrival": {
                "datetime": "20201011091800",
                "station": "Leipzig, Messegel\u00e4nde"
            },
            "sections": [{
                    "from": {
                        "station": "Leipzig, Deutsche Nationalbibliothek",
                        "datetime": "20201011084400",
                        "delay": false,
                        "platform": "",
                        "shifting": 0,
                        "initialDepartureDelay": "00d08:44:00"
                    },
                    "to": {
                        "station": "Leipzig, Messegel\u00e4nde",
                        "datetime": "20201011091800",
                        "delay": false,
                        "platform": "",
                        "shifting": 0,
                        "arrivalDelay": false,
                        "arrivalTime": {
                            "date": "2020-10-11 09:18:00.000000",
                            "timezone_type": 3,
                            "timezone": "Europe\/Berlin"
                        }
                    },
                    "transport": "Str   16",
                    "line": "16",
                    "direction": "Messegel\u00e4nde",
                    "operator": "Leipziger Verkehrsbetriebe",
                    "type": "STN",
                    "duration": "00:34",
                    "delay": "00:34",
                    "length": 21,
                    "special": [],
                    "route": [{
                            "id": 11558,
                            "name": "Leipzig, Deutsche Nationalbibliothek",
                            "lat": 51.323561,
                            "lng": 12.395693,
                            "arr": "08:44",
                            "dep": "08:44",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 11557,
                            "name": "Leipzig, Johannisallee",
                            "lat": 51.3273,
                            "lng": 12.388789,
                            "arr": "08:45",
                            "dep": "08:45",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 10983,
                            "name": "Leipzig, Bayerischer Bahnhof (Tram\/Bus)",
                            "lat": 51.330509,
                            "lng": 12.380906,
                            "arr": "08:47",
                            "dep": "08:47",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 11584,
                            "name": "Leipzig, H\u00e4rtelstr.",
                            "lat": 51.332793,
                            "lng": 12.377544,
                            "arr": "08:49",
                            "dep": "08:49",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 13001,
                            "name": "Leipzig, Ro\u00dfplatz",
                            "lat": 51.336101,
                            "lng": 12.378587,
                            "arr": "08:50",
                            "dep": "08:50",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 13002,
                            "name": "Leipzig, Augustusplatz",
                            "lat": 51.338896,
                            "lng": 12.381994,
                            "arr": "08:52",
                            "dep": "08:52",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 13000,
                            "name": "Leipzig, Hauptbahnhof (Tram\/Bus)",
                            "lat": 51.343948,
                            "lng": 12.380331,
                            "arr": "08:55",
                            "dep": "09:00",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 11410,
                            "name": "Leipzig, Wilhelm-Liebknecht-Platz",
                            "lat": 51.349791,
                            "lng": 12.377589,
                            "arr": "09:02",
                            "dep": "09:02",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12968,
                            "name": "Leipzig, Chausseehaus",
                            "lat": 51.356192,
                            "lng": 12.376996,
                            "arr": "09:04",
                            "dep": "09:04",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12822,
                            "name": "Leipzig, Wilhelminenstr.",
                            "lat": 51.361486,
                            "lng": 12.381391,
                            "arr": "09:05",
                            "dep": "09:05",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 10980,
                            "name": "Leipzig, Eutritzscher Zentrum",
                            "lat": 51.36519,
                            "lng": 12.385185,
                            "arr": "09:06",
                            "dep": "09:06",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12820,
                            "name": "Leipzig, Eutritzscher Markt",
                            "lat": 51.367698,
                            "lng": 12.38629,
                            "arr": "09:08",
                            "dep": "09:08",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12821,
                            "name": "Leipzig, Mosenthinstr.",
                            "lat": 51.372597,
                            "lng": 12.385994,
                            "arr": "09:09",
                            "dep": "09:09",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12818,
                            "name": "Leipzig, Delitzscher\/Essener Str.",
                            "lat": 51.376193,
                            "lng": 12.38549,
                            "arr": "09:10",
                            "dep": "09:10",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12819,
                            "name": "Leipzig, Hornbach-Baumarkt",
                            "lat": 51.378988,
                            "lng": 12.384798,
                            "arr": "09:11",
                            "dep": "09:11",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12816,
                            "name": "Leipzig, Klinikum St. Georg",
                            "lat": 51.384292,
                            "lng": 12.381194,
                            "arr": "09:12",
                            "dep": "09:12",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12823,
                            "name": "Leipzig, Dachauer Str.",
                            "lat": 51.390099,
                            "lng": 12.377193,
                            "arr": "09:14",
                            "dep": "09:14",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12824,
                            "name": "Leipzig, Wiederitzsch, Mitte",
                            "lat": 51.393398,
                            "lng": 12.375683,
                            "arr": "09:15",
                            "dep": "09:15",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 10823,
                            "name": "Leipzig, Georg-Herwegh-Str.",
                            "lat": 51.394881,
                            "lng": 12.383027,
                            "arr": "09:16",
                            "dep": "09:16",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 10824,
                            "name": "Leipzig, S-Bahnhof Messe (Tram\/Bus)",
                            "lat": 51.396041,
                            "lng": 12.388816,
                            "arr": "09:17",
                            "dep": "09:17",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 10818,
                            "name": "Leipzig, Messegel\u00e4nde",
                            "lat": 51.396715,
                            "lng": 12.396574,
                            "arr": "09:18",
                            "dep": "",
                            "hasPrognosis": false,
                            "shifting": 0
                        }
                    ],
                    "color": "#017C46"
                }
            ],
            "types": {
                "stn": true
            },
            "tariffs": {
                "zones": "",
                "zone_start": "",
                "zone_end": ""
            }
        },
        "C1-2": {
            "duration": "00:34",
            "transfers": 0,
            "date": "11.10.2020",
            "departure": {
                "datetime": "20201011091400",
                "station": "Leipzig, Deutsche Nationalbibliothek",
                "shifting": 0,
                "hasPrognosis": {
                    "date": "2020-10-11 09:14:00.000000",
                    "timezone_type": 3,
                    "timezone": "Europe\/Berlin"
                }
            },
            "arrival": {
                "datetime": "20201011094800",
                "station": "Leipzig, Messegel\u00e4nde"
            },
            "sections": [{
                    "from": {
                        "station": "Leipzig, Deutsche Nationalbibliothek",
                        "datetime": "20201011091400",
                        "delay": false,
                        "platform": "",
                        "shifting": 0,
                        "initialDepartureDelay": "00d09:14:00"
                    },
                    "to": {
                        "station": "Leipzig, Messegel\u00e4nde",
                        "datetime": "20201011094800",
                        "delay": false,
                        "platform": "",
                        "shifting": 0,
                        "arrivalDelay": false,
                        "arrivalTime": {
                            "date": "2020-10-11 09:48:00.000000",
                            "timezone_type": 3,
                            "timezone": "Europe\/Berlin"
                        }
                    },
                    "transport": "Str   16",
                    "line": "16",
                    "direction": "Messegel\u00e4nde",
                    "operator": "Leipziger Verkehrsbetriebe",
                    "type": "STN",
                    "duration": "00:34",
                    "delay": "00:34",
                    "length": 21,
                    "special": [],
                    "route": [{
                            "id": 11558,
                            "name": "Leipzig, Deutsche Nationalbibliothek",
                            "lat": 51.323561,
                            "lng": 12.395693,
                            "arr": "09:14",
                            "dep": "09:14",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 11557,
                            "name": "Leipzig, Johannisallee",
                            "lat": 51.3273,
                            "lng": 12.388789,
                            "arr": "09:15",
                            "dep": "09:15",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 10983,
                            "name": "Leipzig, Bayerischer Bahnhof (Tram\/Bus)",
                            "lat": 51.330509,
                            "lng": 12.380906,
                            "arr": "09:17",
                            "dep": "09:17",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 11584,
                            "name": "Leipzig, H\u00e4rtelstr.",
                            "lat": 51.332793,
                            "lng": 12.377544,
                            "arr": "09:19",
                            "dep": "09:19",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 13001,
                            "name": "Leipzig, Ro\u00dfplatz",
                            "lat": 51.336101,
                            "lng": 12.378587,
                            "arr": "09:20",
                            "dep": "09:20",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 13002,
                            "name": "Leipzig, Augustusplatz",
                            "lat": 51.338896,
                            "lng": 12.381994,
                            "arr": "09:22",
                            "dep": "09:22",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 13000,
                            "name": "Leipzig, Hauptbahnhof (Tram\/Bus)",
                            "lat": 51.343948,
                            "lng": 12.380331,
                            "arr": "09:25",
                            "dep": "09:30",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 11410,
                            "name": "Leipzig, Wilhelm-Liebknecht-Platz",
                            "lat": 51.349791,
                            "lng": 12.377589,
                            "arr": "09:32",
                            "dep": "09:32",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12968,
                            "name": "Leipzig, Chausseehaus",
                            "lat": 51.356192,
                            "lng": 12.376996,
                            "arr": "09:34",
                            "dep": "09:34",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12822,
                            "name": "Leipzig, Wilhelminenstr.",
                            "lat": 51.361486,
                            "lng": 12.381391,
                            "arr": "09:35",
                            "dep": "09:35",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 10980,
                            "name": "Leipzig, Eutritzscher Zentrum",
                            "lat": 51.36519,
                            "lng": 12.385185,
                            "arr": "09:36",
                            "dep": "09:36",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12820,
                            "name": "Leipzig, Eutritzscher Markt",
                            "lat": 51.367698,
                            "lng": 12.38629,
                            "arr": "09:38",
                            "dep": "09:38",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12821,
                            "name": "Leipzig, Mosenthinstr.",
                            "lat": 51.372597,
                            "lng": 12.385994,
                            "arr": "09:39",
                            "dep": "09:39",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12818,
                            "name": "Leipzig, Delitzscher\/Essener Str.",
                            "lat": 51.376193,
                            "lng": 12.38549,
                            "arr": "09:40",
                            "dep": "09:40",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12819,
                            "name": "Leipzig, Hornbach-Baumarkt",
                            "lat": 51.378988,
                            "lng": 12.384798,
                            "arr": "09:41",
                            "dep": "09:41",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12816,
                            "name": "Leipzig, Klinikum St. Georg",
                            "lat": 51.384292,
                            "lng": 12.381194,
                            "arr": "09:42",
                            "dep": "09:42",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12823,
                            "name": "Leipzig, Dachauer Str.",
                            "lat": 51.390099,
                            "lng": 12.377193,
                            "arr": "09:44",
                            "dep": "09:44",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 12824,
                            "name": "Leipzig, Wiederitzsch, Mitte",
                            "lat": 51.393398,
                            "lng": 12.375683,
                            "arr": "09:45",
                            "dep": "09:45",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 10823,
                            "name": "Leipzig, Georg-Herwegh-Str.",
                            "lat": 51.394881,
                            "lng": 12.383027,
                            "arr": "09:46",
                            "dep": "09:46",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 10824,
                            "name": "Leipzig, S-Bahnhof Messe (Tram\/Bus)",
                            "lat": 51.396041,
                            "lng": 12.388816,
                            "arr": "09:47",
                            "dep": "09:47",
                            "hasPrognosis": false,
                            "shifting": 0
                        }, {
                            "id": 10818,
                            "name": "Leipzig, Messegel\u00e4nde",
                            "lat": 51.396715,
                            "lng": 12.396574,
                            "arr": "09:48",
                            "dep": "",
                            "hasPrognosis": false,
                            "shifting": 0
                        }
                    ],
                    "color": "#017C46"
                }
            ],
            "types": {
                "stn": true
            },
            "tariffs": {
                "zones": "",
                "zone_start": "",
                "zone_end": ""
            }
        }
    }
    ...
}
```

I've just created a Service hotline ticket at lvb.de. So very likely we get a new version [5][6] ;)

**Comment by juliuste** [comment]
Thanks for the contribution! 🙂 

> A test fails for me

Should we wait or merge this nonetheless?

**Comment by joergreichert** [comment]
I've got response today from LVB support, that they accepted and forwared the issue with the tariff to the "Fachteam", so it is a bug on their side.  So from my point of view this PR can be merged, because all other stuff works so far.

**Review by juliuste — APPROVED** [review]

**Comment by juliuste** [comment]
Published to npm as `1.0.5`

**Pull request merged**
