### PR TITLE
Exchange /fahrplan/haltestelle with fahrplan/abfahrten?ws_info_stop

### PR DESCRIPTION
**Pull request by joergreichert**
currently two tests fail (dnb id and departure, reason is changed URL, this PR will fix this)

### CODE REVIEW

**Comment by hashworks** [comment]
Fix works fine for me, it should be noted that `?ws_info_stop` isn't really needed – but I guess it can't hurt.

**Comment by hashworks** [comment]
Could we merge this?

**Comment by joergreichert** [comment]
Removed unnecessary change in stations.js as well as the superfluous ?ws_info_stop query parameter. So it can be merged now.

**Review by juliuste — APPROVED** [review]

**Comment by juliuste** [comment]
Released as `1.0.6` (sorry about the double version bump, I screwed up 😄)

**Pull request merged**
